### ISSUE TITLE
WebApp completely blocked by Google on 2FA enabled accounts

### ISSUE THREAD

**Issue by SimonARG** [sleepytaco/UnTube#33]
https://i.imgur.com/lwWTAa7.png

For 2FA enabled accounts, Google won't allow access in any way to the account.

**Comment by sleepytaco** [comment]
Hi @SimonARG, thanks for sharing. Apart from your YouTube playlist data, the app only accesses your public Google profile information like name and email. The app isn't verified yet. I plan on getting it verified this summer. My apologies for not getting to this sooner.
