### ISSUE TITLE
error when login to app

### ISSUE THREAD

**Issue by vetsinen** [sleepytaco/UnTube#34]
This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.
![image](https://user-images.githubusercontent.com/28968354/214332610-f555bbaf-7447-4a21-83e7-fadbdaa1e28f.png)

**Comment by sleepytaco** [comment]
Hi @vetsinen, thanks for sharing. Apart from your YouTube playlist data, the app only accesses your public Google profile information like name and email. Someone else had this warning show up as well and I believe it's for accounts with 2FA enabled. The app isn't verified yet. I plan on getting it verified this summer. My apologies for not getting to this sooner.
